---
- name: Install Hawkular APM Server
  hosts: localhost
  vars_files:
    - ansible-vars.yml
  tasks:
    - name: Flush iptables rules
      shell: "sudo iptables -F"

    - name: Create OpenShift Cluster (this might take a while)
      shell: "oc cluster up --version={{ openshift_version }} --metrics={{ openshift_use_metrics }}"
      register: command_result
      when: "create_openshift_cluster"
      failed_when: "'OpenShift is already running' not in command_result.stdout and command_result.rc != 0"

    - name: Create a new OpenShift project
      shell: "oc new-project {{ project_name }}"
      register: command_result
      failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
      changed_when: "'exists' not in command_result.stderr"

    - name: Define OpenShift project
      shell: "oc project {{ project_name }}"

    - name: Install Hawkular APM Server
      shell: "oc create -f hawkular-apm-openshift.yml"
      register: command_result
      failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
      changed_when: "'exists' not in command_result.stderr"
